server:
  port: 8084

grpc:
  port: 9094
  enable-reflection: true

mail:
  transport:
    protocol: smtps
  smtp:
    host: smtp.gmail.com
    port: 587
    user: alyosha.sherbakov
    from: alyosha.sherbakov@gmail.com
    password: "password here"
    auth: true

spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:${spring.datasource.port}/origination
    port: 5432
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

origination:
  client:
    scoring:
      grpc:
        host: localhost
        port: 9096
    agreement:
      grpc:
        host: localhost
        port: 9095
    disbursement:
      grpc:
        host: localhost
        port: 9097